/*
 * trapezoid_velocity_profile.hpp
 *
 *  Created on: Sep 9, 2020
 *      Author: kyberszittya
 */

#ifndef INCLUDE_HOTARU_PLANNER_NODE_BLOCKS_VELOCITY_PROFILE_TRAPEZOID_VELOCITY_PROFILE_HPP_
#define INCLUDE_HOTARU_PLANNER_NODE_BLOCKS_VELOCITY_PROFILE_TRAPEZOID_VELOCITY_PROFILE_HPP_





#endif /* INCLUDE_HOTARU_PLANNER_NODE_BLOCKS_VELOCITY_PROFILE_TRAPEZOID_VELOCITY_PROFILE_HPP_ */
