/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hu.sze.aut.semantics.robotdescription.code.generator;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
