/*
 * test_allocation.hpp
 *
 *  Created on: Feb 19, 2020
 *      Author: kyberszittya
 */

#ifndef INCLUDE_REI_STATEMACHINE_LIBRARY_TESTING_TEST_ALLOCATION_HPP_
#define INCLUDE_REI_STATEMACHINE_LIBRARY_TESTING_TEST_ALLOCATION_HPP_





#endif /* INCLUDE_REI_STATEMACHINE_LIBRARY_TESTING_TEST_ALLOCATION_HPP_ */
